<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBv45ulf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBv45ulf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBv45ulf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBv45ulf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBv45ulf\appProdProjectContainer(array(
    'container.build_hash' => 'Bv45ulf',
    'container.build_id' => '90dba59f',
    'container.build_time' => 1519054606,
));
