<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxwi08v\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxwi08v/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDxwi08v.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDxwi08v\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDxwi08v\appProdProjectContainer(array(
    'container.build_hash' => 'Dxwi08v',
    'container.build_id' => '863ab742',
    'container.build_time' => 1520007096,
));
