vallbona_web_homepage:
    path:     /home
    defaults: { _controller: VallbonaWebBundle:Default:index }

vallbona_web_article:   
    path:     /article
    defaults: { _controller: VallbonaWebBundle:Default:article }

vallbona_web_form:   
    path:     /form-user
    defaults: { _controller: VallbonaWebBundle:Formulari:index }

vallbona_web_createform:   
    path:     /create-user
    defaults: { _controller: VallbonaWebBundle:Formulari:create }

vallbona_web_createformTasca:   
    path:     /create-tasca
    defaults: { _controller: VallbonaWebBundle:FormulariTasca:create }