<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDejadkw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDejadkw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDejadkw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDejadkw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDejadkw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Dejadkw',
    'container.build_id' => '210a0ce0',
    'container.build_time' => 1519313900,
));
