<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNzkf0ds\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNzkf0ds/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNzkf0ds.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNzkf0ds\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNzkf0ds\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nzkf0ds',
    'container.build_id' => 'f3b0a64f',
    'container.build_time' => 1520952058,
));
